### ISSUE TITLE
Sync with Waffle swimlanes

### ISSUE THREAD

**Issue by Baron-burton** [CorporateRewards/flight_plan#13]
- [x] If I move a ticket on the waffle board is the change reflected on Flight Plan?
- [x] If I move a ticket on Flight Plan is the change reflected on the waffle board?
- [x] If a new ticket is created in Github/Waffle does the ticket appear in FlightPlan?
- [x] If a ticket is closed is the ticket also closed on FlightPlan?
- [x] If a ticket's content is edited is the ticket also updated on FlightPlan?
- [x] if comments are added or changes, are the changes reflected in FlightPlan ?
- [x] if a comment is removed on github, is it removed from FlightPlan?
- [ ] does it ignore pull requests

**Comment by jcleary** [comment]
Adding a comment

**Comment by jcleary** [comment]
This is a test comment
